# Generación automática de matrices 4x4

*Nombre:* Danny Jiménez  
*Paralelo:* 1  
*Materia:* Análisis Matricial  
*Tema:* Generación de matrices automáticas con NumPy  

---

Este código permite generar n matrices de tamaño 4x4 bajo una condición lógica seleccionada:

- Fibonacci
- Múltiplos de 5

Las matrices se apilan una debajo de otra automáticamente.

In [2]:
import numpy as np

def generar(n, tipo):
    
    for k in range(n):
        
        if tipo == 1:  # Fibonacci
            a, b = np.random.randint(1,21,2)
            fib = [a, b]
            for i in range(14):
                fib.append(fib[-1] + fib[-2])
            m = np.array(fib).reshape(4,4)
            nombre = "Fibonacci"
        
        else:  # Multiplos de 5
            inicio = np.random.randint(1,20)
            m = np.arange(inicio, inicio + 5*16, 5).reshape(4,4)
            nombre = "Multiplos de 5"
        
        print(f"\nMatriz {k+1} ({nombre})")
        print(m)


n = int(input("Ingrese número de matrices: "))
tipo = int(input("1 Fibonacci | 2 Multiplos de 5: "))

print(f"\nGenerando {n} matrices de 4x4\n")

generar(n, tipo)


Generando 4 matrices de 4x4


Matriz 1 (Fibonacci)
[[   4    1    5    6]
 [  11   17   28   45]
 [  73  118  191  309]
 [ 500  809 1309 2118]]

Matriz 2 (Fibonacci)
[[   14    10    24    34]
 [   58    92   150   242]
 [  392   634  1026  1660]
 [ 2686  4346  7032 11378]]

Matriz 3 (Fibonacci)
[[    6    15    21    36]
 [   57    93   150   243]
 [  393   636  1029  1665]
 [ 2694  4359  7053 11412]]

Matriz 4 (Fibonacci)
[[   15     9    24    33]
 [   57    90   147   237]
 [  384   621  1005  1626]
 [ 2631  4257  6888 11145]]
